// 対象シートの定義
export const TARGET_SHEETS = ["PL", "BS", "CAPEX", "CS"];

// パラメータタイプの選択肢
export const PARAMETER_TYPES = [
  "NONE",
  "GROWTH_RATE",
  "PERCENTAGE",
  "PROPORTIONATE",
  "FIXED_VALUE",
  "CHILDREN_SUM",
  "PPE",
  "CAPITAL_INCREASE_AND_DIVIDENDS",
];

// リレーションタイプの定義
export const RELATION_TYPES = {
  NONE: null,
  PPE: "PPE",
  RETAINED_EARNINGS: "RETAINED_EARNINGS",
  WORKING_CAPITAL: "WORKING_CAPITAL",
};

// リレーションサブタイプの定義
export const RELATION_SUB_TYPES = {
  PROFIT: "PROFIT",
  ASSET: "ASSET",
  FIXED_ASSET: "FIXED_ASSET",
  INVESTMENT: "INVESTMENT",
  DEPRECIATION: "DEPRECIATION",
  RETAINED: "RETAINED",
  DIVIDEND: "DIVIDEND",
  WC_ASSET: "WC_ASSET",
  WC_LIABILITY: "WC_LIABILITY",
};

// 集計用勘定科目の定義
export const SUMMARY_ACCOUNTS = {
  // PLアカウント
  売上高合計: {
    id: "rev-total",
    accountName: "売上高合計",
    sheetType: "PL",
    parentAccount: "SUMMARY_ACCOUNTS",
    parameterType: "CHILDREN_SUM",
    isParameterReference: true,
    order: "A99",
    prefix: "A",
    relation: { type: RELATION_TYPES.NONE, subType: null },
  },
  売上原価合計: {
    id: "cogs-total",
    accountName: "売上原価合計",
    sheetType: "PL",
    parentAccount: "SUMMARY_ACCOUNTS",
    parameterType: "CHILDREN_SUM",
    isParameterReference: false,
    order: "B99",
    prefix: "B",
    relation: { type: RELATION_TYPES.NONE, subType: null },
  },
  売上総利益: {
    id: "gross-profit",
    accountName: "売上総利益",
    sheetType: "PL",
    parentAccount: "SUMMARY_ACCOUNTS",
    calculationType: "ACCOUNT_CALC",
    parameterType: null,
    isParameterReference: false,
    order: "C99",
    prefix: "C",
    relation: { type: RELATION_TYPES.NONE, subType: null },
    dependencies: {
      depends_on: ["rev-total", "cogs-total"],
    },
  },
  販管費合計: {
    id: "sga-total",
    accountName: "販管費合計",
    sheetType: "PL",
    parentAccount: "SUMMARY_ACCOUNTS",
    parameterType: "CHILDREN_SUM",
    isParameterReference: false,
    order: "D99",
    prefix: "D",
    relation: { type: RELATION_TYPES.NONE, subType: null },
  },
  営業利益: {
    id: "op-profit",
    accountName: "営業利益",
    sheetType: "PL",
    parentAccount: "SUMMARY_ACCOUNTS",
    calculationType: "ACCOUNT_CALC",
    parameterType: null,
    isParameterReference: false,
    order: "E99",
    prefix: "E",
    relation: {
      type: RELATION_TYPES.RETAINED_EARNINGS,
      subType: RELATION_SUB_TYPES.PROFIT,
    },
    dependencies: {
      depends_on: ["gross-profit", "sga-total"],
    },
  },

  // BSアカウント - 親子関係の階層構造を明確化
  流動資産合計: {
    id: "current-asset-total",
    accountName: "流動資産合計",
    sheetType: "BS",
    parentAccount: "資産合計",
    parameterType: "CHILDREN_SUM",
    isParameterReference: false,
    order: "F99",
    prefix: "F",
    relation: { type: RELATION_TYPES.NONE, subType: null },
  },
  固定資産合計: {
    id: "fixed-asset-total",
    accountName: "固定資産合計",
    sheetType: "BS",
    parentAccount: "資産合計",
    parameterType: "CHILDREN_SUM",
    isParameterReference: false,
    order: "G99",
    prefix: "G",
    relation: { type: RELATION_TYPES.NONE, subType: null },
  },
  資産合計: {
    id: "asset-total",
    accountName: "資産合計",
    sheetType: "BS",
    parentAccount: "SUMMARY_ACCOUNTS",
    parameterType: "CHILDREN_SUM",
    isParameterReference: false,
    order: "H99",
    prefix: "H",
    relation: { type: RELATION_TYPES.NONE, subType: null },
  },
  流動負債合計: {
    id: "current-liability-total",
    accountName: "流動負債合計",
    sheetType: "BS",
    parentAccount: "負債合計",
    parameterType: "CHILDREN_SUM",
    isParameterReference: false,
    order: "I99",
    prefix: "I",
    relation: { type: RELATION_TYPES.NONE, subType: null },
  },
  固定負債合計: {
    id: "fixed-liability-total",
    accountName: "固定負債合計",
    sheetType: "BS",
    parentAccount: "負債合計",
    parameterType: "CHILDREN_SUM",
    isParameterReference: false,
    order: "J99",
    prefix: "J",
    relation: { type: RELATION_TYPES.NONE, subType: null },
  },
  負債合計: {
    id: "liability-total",
    accountName: "負債合計",
    sheetType: "BS",
    parentAccount: "負債及び純資産合計",
    parameterType: "CHILDREN_SUM",
    isParameterReference: false,
    order: "K99",
    prefix: "K",
    relation: { type: RELATION_TYPES.NONE, subType: null },
  },
  純資産合計: {
    id: "equity-total",
    accountName: "純資産合計",
    sheetType: "BS",
    parentAccount: "負債及び純資産合計",
    parameterType: "CHILDREN_SUM",
    isParameterReference: false,
    order: "N99",
    prefix: "N",
    relation: { type: RELATION_TYPES.NONE, subType: null },
  },
  負債及び純資産合計: {
    id: "li-eq-total",
    accountName: "負債及び純資産合計",
    sheetType: "BS",
    parentAccount: "SUMMARY_ACCOUNTS",
    parameterType: "CHILDREN_SUM",
    isParameterReference: false,
    order: "O99",
    prefix: "O",
    relation: { type: RELATION_TYPES.NONE, subType: null },
  },

  // CAPEXアカウント
  設備投資合計: {
    id: "capex-total",
    accountName: "設備投資合計",
    sheetType: "CAPEX",
    parentAccount: "SUMMARY_ACCOUNTS",
    parameterType: "CHILDREN_SUM",
    isParameterReference: false,
    order: "Q99",
    prefix: "Q",
    relation: { type: RELATION_TYPES.NONE, subType: null },
  },

  // CFアカウント
  営業CF合計: {
    id: "ope-cf-total",
    accountName: "営業CF合計",
    sheetType: "CF",
    parentAccount: "SUMMARY_ACCOUNTS",
    parameterType: "CHILDREN_SUM",
    isParameterReference: false,
    order: "R99",
    prefix: "R",
    relation: { type: RELATION_TYPES.NONE, subType: null },
  },
  投資CF合計: {
    id: "inv-cf-total",
    accountName: "投資CF合計",
    sheetType: "CF",
    parentAccount: "SUMMARY_ACCOUNTS",
    parameterType: "CHILDREN_SUM",
    isParameterReference: false,
    order: "S99",
    prefix: "S",
    relation: { type: RELATION_TYPES.NONE, subType: null },
  },
};

// 勘定科目デフォルトシートタイプマッピング
export const DEFAULT_SHEET_TYPES = {
  商品売上: {
    sheetType: "PL",
    parentAccount: "売上高合計",
    parameterType: "GROWTH_RATE",
    relation: { type: RELATION_TYPES.NONE, subType: null },
  },
  サービス売上: {
    sheetType: "PL",
    parentAccount: "売上高合計",
    parameterType: "GROWTH_RATE",
    relation: { type: RELATION_TYPES.NONE, subType: null },
  },
  その他売上: {
    sheetType: "PL",
    parentAccount: "売上高合計",
    parameterType: "GROWTH_RATE",
    relation: { type: RELATION_TYPES.NONE, subType: null },
  },
  売上高合計: {
    sheetType: "集約科目",
    parentAccount: "集約科目",
    parameterType: "NONE",
    relation: { type: RELATION_TYPES.NONE, subType: null },
  },
  材料費: {
    sheetType: "PL",
    parentAccount: "売上原価合計",
    parameterType: "PROPORTIONATE",
    relation: { type: RELATION_TYPES.NONE, subType: null },
  },
  労務費: {
    sheetType: "PL",
    parentAccount: "売上原価合計",
    parameterType: "FIXED_VALUE",
    relation: { type: RELATION_TYPES.NONE, subType: null },
  },
  売上原価合計: {
    sheetType: "集約科目",
    parentAccount: "集約科目",
    parameterType: "NONE",
    relation: { type: RELATION_TYPES.NONE, subType: null },
  },
  売上総利益: {
    sheetType: "集約科目",
    parentAccount: "集約科目",
    parameterType: "NONE",
    relation: { type: RELATION_TYPES.NONE, subType: null },
  },
  人件費: {
    sheetType: "PL",
    parentAccount: "販管費合計",
    parameterType: "FIXED_VALUE",
    relation: { type: RELATION_TYPES.NONE, subType: null },
  },
  物流費: {
    sheetType: "PL",
    parentAccount: "販管費合計",
    parameterType: "PROPORTIONATE",
    relation: { type: RELATION_TYPES.NONE, subType: null },
  },
  減価償却費_PL: {
    sheetType: "PL",
    parentAccount: "販管費合計",
    parameterType: "PROPORTIONATE",
    relation: {
      type: RELATION_TYPES.PPE,
      subType: RELATION_SUB_TYPES.DEPRECIATION,
    },
  },
  無形固定資産償却費_PL: {
    sheetType: "PL",
    parentAccount: "販管費合計",
    parameterType: "FIXED_VALUE",
    relation: {
      type: RELATION_TYPES.PPE,
      subType: RELATION_SUB_TYPES.DEPRECIATION,
    },
  },
  その他販管費: {
    sheetType: "PL",
    parentAccount: "販管費合計",
    parameterType: "PERCENTAGE",
    relation: { type: RELATION_TYPES.NONE, subType: null },
  },
  販管費合計: {
    sheetType: "集約科目",
    parentAccount: "集約科目",
    parameterType: "NONE",
    relation: { type: RELATION_TYPES.NONE, subType: null },
  },
  営業利益: {
    sheetType: "集約科目",
    parentAccount: "集約科目",
    parameterType: "NONE",
    relation: {
      type: RELATION_TYPES.RETAINED_EARNINGS,
      subType: RELATION_SUB_TYPES.PROFIT,
    },
  },
  現預金: {
    sheetType: "BS",
    parentAccount: "流動資産合計",
    parameterType: "PROPORTIONATE",
    relation: { type: RELATION_TYPES.NONE, subType: null },
  },
  売掛金: {
    sheetType: "BS",
    parentAccount: "流動資産合計",
    parameterType: "PROPORTIONATE",
    relation: {
      type: RELATION_TYPES.WORKING_CAPITAL,
      subType: RELATION_SUB_TYPES.WC_ASSET,
    },
  },
  棚卸資産: {
    sheetType: "BS",
    parentAccount: "流動資産合計",
    parameterType: "PROPORTIONATE",
    relation: {
      type: RELATION_TYPES.WORKING_CAPITAL,
      subType: RELATION_SUB_TYPES.WC_ASSET,
    },
  },
  流動資産合計: {
    sheetType: "集約科目",
    parentAccount: "集約科目",
    parameterType: "NONE",
    relation: { type: RELATION_TYPES.NONE, subType: null },
  },
  有形固定資産: {
    sheetType: "BS",
    parentAccount: "固定資産合計",
    parameterType: "PROPORTIONATE",
    calculationType: "ACCOUNT_CALC",
    relation: { type: RELATION_TYPES.PPE, subType: RELATION_SUB_TYPES.ASSET },
  },
  無形固定資産: {
    sheetType: "BS",
    parentAccount: "固定資産合計",
    parameterType: "PROPORTIONATE",
    relation: { type: RELATION_TYPES.PPE, subType: RELATION_SUB_TYPES.ASSET },
  },
  固定資産合計: {
    sheetType: "集約科目",
    parentAccount: "集約科目",
    parameterType: "NONE",
    relation: { type: RELATION_TYPES.NONE, subType: null },
  },
  資産合計: {
    sheetType: "集約科目",
    parentAccount: "集約科目",
    parameterType: "NONE",
    relation: { type: RELATION_TYPES.NONE, subType: null },
  },
  買掛金: {
    sheetType: "BS",
    parentAccount: "流動負債合計",
    parameterType: "PROPORTIONATE",
    relation: {
      type: RELATION_TYPES.WORKING_CAPITAL,
      subType: RELATION_SUB_TYPES.WC_LIABILITY,
    },
  },
  支払手形: {
    sheetType: "BS",
    parentAccount: "流動負債合計",
    parameterType: "PROPORTIONATE",
    relation: {
      type: RELATION_TYPES.WORKING_CAPITAL,
      subType: RELATION_SUB_TYPES.WC_LIABILITY,
    },
  },
  流動負債合計: {
    sheetType: "集約科目",
    parentAccount: "集約科目",
    parameterType: "NONE",
    relation: { type: RELATION_TYPES.NONE, subType: null },
  },
  長期借入金: {
    sheetType: "BS",
    parentAccount: "固定負債合計",
    parameterType: "PROPORTIONATE",
    relation: { type: RELATION_TYPES.NONE, subType: null },
  },
  社債: {
    sheetType: "BS",
    parentAccount: "固定負債合計",
    parameterType: "PROPORTIONATE",
    relation: { type: RELATION_TYPES.NONE, subType: null },
  },
  固定負債合計: {
    sheetType: "集約科目",
    parentAccount: "集約科目",
    parameterType: "NONE",
    relation: { type: RELATION_TYPES.NONE, subType: null },
  },
  負債合計: {
    sheetType: "集約科目",
    parentAccount: "集約科目",
    parameterType: "NONE",
    relation: { type: RELATION_TYPES.NONE, subType: null },
  },
  資本金: {
    sheetType: "BS",
    parentAccount: "純資産合計",
    parameterType: "PROPORTIONATE",
    relation: { type: RELATION_TYPES.NONE, subType: null },
  },
  利益剰余金: {
    sheetType: "BS",
    parentAccount: "純資産合計",
    parameterType: "PROPORTIONATE",
    relation: {
      type: RELATION_TYPES.RETAINED_EARNINGS,
      subType: RELATION_SUB_TYPES.RETAINED,
    },
  },
  純資産合計: {
    sheetType: "集約科目",
    parentAccount: "集約科目",
    parameterType: "NONE",
    relation: { type: RELATION_TYPES.NONE, subType: null },
  },
  負債及び純資産合計: {
    sheetType: "集約科目",
    parentAccount: "集約科目",
    parameterType: "NONE",
    relation: { type: RELATION_TYPES.NONE, subType: null },
  },
  有形資産投資: {
    sheetType: "CAPEX",
    parentAccount: "設備投資合計",
    parameterType: "PROPORTIONATE",
    relation: {
      type: RELATION_TYPES.PPE,
      subType: RELATION_SUB_TYPES.INVESTMENT,
    },
  },
  無形資産投資: {
    sheetType: "CAPEX",
    parentAccount: "設備投資合計",
    parameterType: "PROPORTIONATE",
    relation: {
      type: RELATION_TYPES.PPE,
      subType: RELATION_SUB_TYPES.INVESTMENT,
    },
  },
  設備投資合計: {
    sheetType: "集約科目",
    parentAccount: "集約科目",
    parameterType: "NONE",
    relation: { type: RELATION_TYPES.NONE, subType: null },
  },
  営業利益_CF: {
    sheetType: "集約科目",
    parentAccount: "営業CF合計",
    parameterType: "NONE",
    relation: { type: RELATION_TYPES.NONE, subType: null },
  },
  減価償却費_CF: {
    sheetType: "CF",
    parentAccount: "営業CF合計",
    parameterType: "NONE",
    relation: { type: RELATION_TYPES.NONE, subType: null },
  },
  無形固定資産償却費_CF: {
    sheetType: "CF",
    parentAccount: "営業CF合計",
    parameterType: "NONE",
    relation: { type: RELATION_TYPES.NONE, subType: null },
  },
  運転資本増減: {
    sheetType: "CF",
    parentAccount: "営業CF合計",
    parameterType: "NONE",
    relation: { type: RELATION_TYPES.NONE, subType: null },
  },
  営業CF合計: {
    sheetType: "集約科目",
    parentAccount: "集約科目",
    parameterType: "NONE",
    relation: { type: RELATION_TYPES.NONE, subType: null },
  },
  設備投資合計_CF: {
    sheetType: "CF",
    parentAccount: "投資CF合計",
    parameterType: "NONE",
    relation: { type: RELATION_TYPES.NONE, subType: null },
  },
  投資CF合計: {
    sheetType: "集約科目",
    parentAccount: "集約科目",
    parameterType: "NONE",
    relation: { type: RELATION_TYPES.NONE, subType: null },
  },

  // MODEL_ACCOUNTSから追加された科目
  売上高1: {
    sheetType: "PL",
    parentAccount: "売上高合計",
    parameterType: "GROWTH_RATE",
    relation: { type: RELATION_TYPES.NONE, subType: null },
  },
  売上高2: {
    sheetType: "PL",
    parentAccount: "売上高合計",
    parameterType: "GROWTH_RATE",
    relation: { type: RELATION_TYPES.NONE, subType: null },
  },
  売上原価1: {
    sheetType: "PL",
    parentAccount: "売上原価合計",
    parameterType: "PERCENTAGE",
    relation: { type: RELATION_TYPES.NONE, subType: null },
  },
  売上原価2: {
    sheetType: "PL",
    parentAccount: "売上原価合計",
    parameterType: "PERCENTAGE",
    relation: { type: RELATION_TYPES.NONE, subType: null },
  },
  広告宣伝費: {
    sheetType: "PL",
    parentAccount: "販管費合計",
    parameterType: "PERCENTAGE",
    relation: { type: RELATION_TYPES.NONE, subType: null },
  },
  物件費: {
    sheetType: "PL",
    parentAccount: "販管費合計",
    parameterType: "PERCENTAGE",
    relation: { type: RELATION_TYPES.NONE, subType: null },
  },
  その他償却費1: {
    sheetType: "PL",
    parentAccount: "販管費合計",
    parameterType: "PERCENTAGE",
    relation: {
      type: RELATION_TYPES.PPE,
      subType: RELATION_SUB_TYPES.DEPRECIATION,
    },
  },
  その他償却費2: {
    sheetType: "PL",
    parentAccount: "販管費合計",
    parameterType: "PERCENTAGE",
    relation: {
      type: RELATION_TYPES.PPE,
      subType: RELATION_SUB_TYPES.DEPRECIATION,
    },
  },
  その他流動資産: {
    sheetType: "BS",
    parentAccount: "流動資産合計",
    parameterType: "PROPORTIONATE",
    relation: { type: RELATION_TYPES.NONE, subType: null },
  },
  償却資産1: {
    sheetType: "BS",
    parentAccount: "固定資産合計",
    parameterType: "PROPORTIONATE",
    relation: { type: RELATION_TYPES.PPE, subType: RELATION_SUB_TYPES.ASSET },
  },
  償却資産2: {
    sheetType: "BS",
    parentAccount: "固定資産合計",
    parameterType: "PROPORTIONATE",
    relation: { type: RELATION_TYPES.PPE, subType: RELATION_SUB_TYPES.ASSET },
  },
  その他固定資産: {
    sheetType: "BS",
    parentAccount: "固定資産合計",
    parameterType: "PROPORTIONATE",
    relation: { type: RELATION_TYPES.NONE, subType: null },
  },
  その他流動負債: {
    sheetType: "BS",
    parentAccount: "流動負債合計",
    parameterType: "PROPORTIONATE",
    relation: { type: RELATION_TYPES.NONE, subType: null },
  },
  その他固定負債: {
    sheetType: "BS",
    parentAccount: "固定負債合計",
    parameterType: "PROPORTIONATE",
    relation: { type: RELATION_TYPES.NONE, subType: null },
  },
  固定資産投資1: {
    sheetType: "CAPEX",
    parentAccount: "設備投資合計",
    parameterType: "PROPORTIONATE",
    relation: {
      type: RELATION_TYPES.PPE,
      subType: RELATION_SUB_TYPES.INVESTMENT,
    },
  },
  固定資産投資2: {
    sheetType: "CAPEX",
    parentAccount: "設備投資合計",
    parameterType: "PROPORTIONATE",
    relation: {
      type: RELATION_TYPES.PPE,
      subType: RELATION_SUB_TYPES.INVESTMENT,
    },
  },
};

// モデルの勘定科目リスト（元の勘定科目 + 集計科目）
export const MODEL_ACCOUNTS = [
  "売上高1",
  "売上高2",
  "売上原価1",
  "売上原価2",
  "人件費",
  "広告宣伝費",
  "物件費",
  "減価償却費_PL",
  "無形固定資産償却費_PL",
  "その他償却費1",
  "その他償却費2",
  "その他販管費",
  "現預金",
  "売掛金",
  "棚卸資産",
  "その他流動資産",
  "償却資産1",
  "償却資産2",
  "その他固定資産",
  "買掛金",
  "支払手形",
  "その他流動負債",
  "長期借入金",
  "その他固定負債",
  "資本金等",
  "利益剰余金等",
  "固定資産投資1",
  "固定資産投資2",
  "減価償却費_CF",
  "無形固定資産償却費_CF",
];
