import { AccountType, ParameterType, CashflowType } from "../types/models.js";

// パラメータのデフォルト値
export const DEFAULT_PARAMETER_VALUES = {
  // export const ParameterType = {
  // GROWTH_RATE: "GROWTH_RATE", 成長率（前年比）
  // PERCENTAGE: "PERCENTAGE", 割合（参照値に対する割合）
  // FIXED_VALUE: "FIXED_VALUE", 固定値
  // PROPORTIONATE: "PROPORTIONATE", 参照科目の増減率に連動
  // OTHER: "OTHER", // その他の特殊計算
  // };
  // [ParameterType.GROWTH_RATE]は結局"GROWTH_RATE"
  // →ParameterType.GROWTH_RATE が "ANNUAL_GROWTH"に変わった時も変更不要
  [ParameterType.GROWTH_RATE]: 10.0, // 10% 成長
  [ParameterType.PERCENTAGE]: 30.0, // 30% の割合
  [ParameterType.PROPORTIONATE]: null, // 参照科目に連動するため値はnull
  [ParameterType.OTHER]: null, // 特殊計算用
};

// 参照科目IDのリスト
export const INITIAL_REFERENCE_ACCOUNTS = [
  "rev-total", // 売上高合計
  "asset-total", // 資産合計
  "op-profit", // 営業利益
  "li-eq-total", // 負債及び純資産合計
];

// 集計用勘定科目の定義
export const SUMMARY_ACCOUNTS = {
  // PLアカウント
  売上高合計: {
    id: "rev-total",
    accountName: "売上高合計",
    sheetType: "PL",
    parentAccount: null,
    calculationType: "CHILDREN_SUM",
    parameterType: null,
    isParameterReference: true,
    order: "A99",
    prefix: "A",
    relation: { type: "NONE", subType: null },
  },
  売上原価合計: {
    id: "cogs-total",
    accountName: "売上原価合計",
    sheetType: "PL",
    parentAccount: null,
    calculationType: "CHILDREN_SUM",
    parameterType: null,
    isParameterReference: false,
    order: "B99",
    prefix: "B",
    relation: { type: "NONE", subType: null },
  },
  売上総利益: {
    id: "gross-profit",
    accountName: "売上総利益",
    sheetType: "PL",
    parentAccount: null,
    calculationType: "ACCOUNT_CALC",
    parameterType: null,
    isParameterReference: false,
    order: "C99",
    prefix: "C",
    relation: { type: "NONE", subType: null },
    dependencies: {
      depends_on: ["rev-total", "cogs-total"],
    },
  },
  販管費合計: {
    id: "sga-total",
    accountName: "販管費合計",
    sheetType: "PL",
    parentAccount: null,
    calculationType: "CHILDREN_SUM",
    parameterType: null,
    isParameterReference: false,
    order: "D99",
    prefix: "D",
    relation: { type: "NONE", subType: null },
  },
  営業利益: {
    id: "op-profit",
    accountName: "営業利益",
    sheetType: "PL",
    parentAccount: null,
    calculationType: "ACCOUNT_CALC",
    parameterType: null,
    isParameterReference: false,
    order: "E99",
    prefix: "E",
    relation: { type: "RETAINED_EARNINGS", subType: "profit" },
    dependencies: {
      depends_on: ["gross-profit", "sga-total"],
    },
  },

  // BSアカウント - 親子関係の階層構造を明確化
  流動資産合計: {
    id: "current-asset-total",
    accountName: "流動資産合計",
    sheetType: "BS",
    parentAccount: "資産合計",
    calculationType: "CHILDREN_SUM",
    parameterType: null,
    isParameterReference: false,
    order: "F99",
    prefix: "F",
    relation: { type: "NONE", subType: null },
  },
  固定資産合計: {
    id: "fixed-asset-total",
    accountName: "固定資産合計",
    sheetType: "BS",
    parentAccount: "資産合計",
    calculationType: "CHILDREN_SUM",
    parameterType: null,
    isParameterReference: false,
    order: "G99",
    prefix: "G",
    relation: { type: "NONE", subType: null },
  },
  資産合計: {
    id: "asset-total",
    accountName: "資産合計",
    sheetType: "BS",
    parentAccount: null,
    calculationType: "CHILDREN_SUM",
    parameterType: null,
    isParameterReference: false,
    order: "H99",
    prefix: "H",
    relation: { type: "NONE", subType: null },
  },
  流動負債合計: {
    id: "current-liability-total",
    accountName: "流動負債合計",
    sheetType: "BS",
    parentAccount: "負債合計",
    calculationType: "CHILDREN_SUM",
    parameterType: null,
    isParameterReference: false,
    order: "I99",
    prefix: "I",
    relation: { type: "NONE", subType: null },
  },
  固定負債合計: {
    id: "fixed-liability-total",
    accountName: "固定負債合計",
    sheetType: "BS",
    parentAccount: "負債合計",
    calculationType: "CHILDREN_SUM",
    parameterType: null,
    isParameterReference: false,
    order: "J99",
    prefix: "J",
    relation: { type: "NONE", subType: null },
  },
  負債合計: {
    id: "liability-total",
    accountName: "負債合計",
    sheetType: "BS",
    parentAccount: "負債及び純資産合計",
    calculationType: "CHILDREN_SUM",
    parameterType: null,
    isParameterReference: false,
    order: "K99",
    prefix: "K",
    relation: { type: "NONE", subType: null },
  },
  資本金: {
    id: "equity",
    accountName: "資本金",
    sheetType: "BS",
    parentAccount: "純資産合計",
    calculationType: "CHILDREN_SUM",
    parameterType: "PROPORTIONATE",
    isParameterReference: false,
    order: "L99",
    prefix: "L",
    relation: { type: "NONE", subType: null },
  },
  利益剰余金: {
    id: "retained-earnings",
    accountName: "利益剰余金",
    sheetType: "BS",
    parentAccount: "純資産合計",
    calculationType: "CHILDREN_SUM",
    parameterType: "PROPORTIONATE",
    isParameterReference: false,
    order: "M99",
    prefix: "M",
    relation: { type: "RETAINED_EARNINGS", subType: "asset" },
  },
  純資産合計: {
    id: "equity-total",
    accountName: "純資産合計",
    sheetType: "BS",
    parentAccount: "負債及び純資産合計",
    calculationType: "CHILDREN_SUM",
    parameterType: null,
    isParameterReference: false,
    order: "N99",
    prefix: "N",
    relation: { type: "NONE", subType: null },
  },
  負債及び純資産合計: {
    id: "li-eq-total",
    accountName: "負債及び純資産合計",
    sheetType: "BS",
    parentAccount: null,
    calculationType: "CHILDREN_SUM",
    parameterType: null,
    isParameterReference: false,
    order: "O99",
    prefix: "O",
    relation: { type: "NONE", subType: null },
  },
  チェック: {
    id: "check",
    accountName: "チェック",
    sheetType: "BS",
    parentAccount: null,
    calculationType: "CHILDREN_SUM",
    parameterType: "OTHER",
    isParameterReference: false,
    order: "P99",
    prefix: "P",
    relation: { type: "NONE", subType: null },
  },

  // CAPEXアカウント
  設備投資合計: {
    id: "capex-total",
    accountName: "設備投資合計",
    sheetType: "CAPEX",
    parentAccount: null,
    calculationType: "CHILDREN_SUM",
    parameterType: null,
    isParameterReference: false,
    order: "Q99",
    prefix: "Q",
    relation: { type: "NONE", subType: null },
  },

  // CFアカウント
  営業CF合計: {
    id: "ope-cf-total",
    accountName: "営業CF合計",
    sheetType: "CF",
    parentAccount: null,
    calculationType: "CHILDREN_SUM",
    parameterType: null,
    isParameterReference: false,
    order: "R99",
    prefix: "R",
    relation: { type: "NONE", subType: null },
  },
  投資CF合計: {
    id: "inv-cf-total",
    accountName: "投資CF合計",
    sheetType: "CF",
    parentAccount: null,
    calculationType: "CHILDREN_SUM",
    parameterType: null,
    isParameterReference: false,
    order: "S99",
    prefix: "S",
    relation: { type: "NONE", subType: null },
  },
};

// 勘定科目デフォルトシートタイプマッピング
export const DEFAULT_SHEET_TYPES = {
  商品売上: {
    sheetType: "PL",
    parentAccount: "売上高合計",
    parameterType: "GROWTH_RATE",
    relation: { type: "NONE", subType: null },
  },
  サービス売上: {
    sheetType: "PL",
    parentAccount: "売上高合計",
    parameterType: "GROWTH_RATE",
    relation: { type: "NONE", subType: null },
  },
  その他売上: {
    sheetType: "PL",
    parentAccount: "売上高合計",
    parameterType: "GROWTH_RATE",
    relation: { type: "NONE", subType: null },
  },
  売上高合計: {
    sheetType: "集約科目",
    parentAccount: "",
    parameterType: "NONE",
    relation: { type: "NONE", subType: null },
  },
  材料費: {
    sheetType: "PL",
    parentAccount: "売上原価合計",
    parameterType: "PERCENTAGE",
    relation: { type: "NONE", subType: null },
  },
  労務費: {
    sheetType: "PL",
    parentAccount: "売上原価合計",
    parameterType: "PERCENTAGE",
    relation: { type: "NONE", subType: null },
  },
  売上原価合計: {
    sheetType: "集約科目",
    parentAccount: "",
    parameterType: "NONE",
    relation: { type: "NONE", subType: null },
  },
  売上総利益: {
    sheetType: "集約科目",
    parentAccount: "",
    parameterType: "NONE",
    relation: { type: "NONE", subType: null },
  },
  人件費: {
    sheetType: "PL",
    parentAccount: "販管費合計",
    parameterType: "PERCENTAGE",
    relation: { type: "NONE", subType: null },
  },
  物流費: {
    sheetType: "PL",
    parentAccount: "販管費合計",
    parameterType: "PERCENTAGE",
    relation: { type: "NONE", subType: null },
  },
  減価償却費_PL: {
    sheetType: "PL",
    parentAccount: "販管費合計",
    parameterType: "PERCENTAGE",
    relation: { type: "PPE", subType: "depreciation" },
  },
  無形固定資産償却費_PL: {
    sheetType: "PL",
    parentAccount: "販管費合計",
    parameterType: "PERCENTAGE",
    relation: { type: "PPE", subType: "depreciation" },
  },
  その他販管費: {
    sheetType: "PL",
    parentAccount: "販管費合計",
    parameterType: "PERCENTAGE",
    relation: { type: "NONE", subType: null },
  },
  販管費合計: {
    sheetType: "集約科目",
    parentAccount: "",
    parameterType: "NONE",
    relation: { type: "NONE", subType: null },
  },
  営業利益: {
    sheetType: "集約科目",
    parentAccount: "",
    parameterType: "NONE",
    relation: { type: "RETAINED_EARNINGS", subType: "profit" },
  },
  現預金: {
    sheetType: "BS",
    parentAccount: "流動資産合計",
    parameterType: "PROPORTIONATE",
    relation: { type: "NONE", subType: null },
  },
  売掛金: {
    sheetType: "BS",
    parentAccount: "流動資産合計",
    parameterType: "PROPORTIONATE",
    relation: { type: "NONE", subType: null },
  },
  棚卸資産: {
    sheetType: "BS",
    parentAccount: "流動資産合計",
    parameterType: "PROPORTIONATE",
    relation: { type: "NONE", subType: null },
  },
  流動資産合計: {
    sheetType: "集約科目",
    parentAccount: "",
    parameterType: "NONE",
    relation: { type: "NONE", subType: null },
  },
  有形固定資産: {
    sheetType: "BS",
    parentAccount: "固定資産合計",
    parameterType: "PROPORTIONATE",
    relation: { type: "PPE", subType: "asset" },
  },
  無形固定資産: {
    sheetType: "BS",
    parentAccount: "固定資産合計",
    parameterType: "PROPORTIONATE",
    relation: { type: "PPE", subType: "asset" },
  },
  固定資産合計: {
    sheetType: "集約科目",
    parentAccount: "",
    parameterType: "NONE",
    relation: { type: "NONE", subType: null },
  },
  資産合計: {
    sheetType: "集約科目",
    parentAccount: "",
    parameterType: "NONE",
    relation: { type: "NONE", subType: null },
  },
  買掛金: {
    sheetType: "BS",
    parentAccount: "流動負債合計",
    parameterType: "PROPORTIONATE",
    relation: { type: "NONE", subType: null },
  },
  支払手形: {
    sheetType: "BS",
    parentAccount: "流動負債合計",
    parameterType: "PROPORTIONATE",
    relation: { type: "NONE", subType: null },
  },
  流動負債合計: {
    sheetType: "集約科目",
    parentAccount: "",
    parameterType: "NONE",
    relation: { type: "NONE", subType: null },
  },
  長期借入金: {
    sheetType: "BS",
    parentAccount: "固定負債合計",
    parameterType: "PROPORTIONATE",
    relation: { type: "NONE", subType: null },
  },
  社債: {
    sheetType: "BS",
    parentAccount: "固定負債合計",
    parameterType: "PROPORTIONATE",
    relation: { type: "NONE", subType: null },
  },
  固定負債合計: {
    sheetType: "集約科目",
    parentAccount: "",
    parameterType: "NONE",
    relation: { type: "NONE", subType: null },
  },
  負債合計: {
    sheetType: "集約科目",
    parentAccount: "",
    parameterType: "NONE",
    relation: { type: "NONE", subType: null },
  },
  資本金: {
    sheetType: "BS",
    parentAccount: "純資産合計",
    parameterType: "PROPORTIONATE",
    relation: { type: "NONE", subType: null },
  },
  利益剰余金: {
    sheetType: "BS",
    parentAccount: "純資産合計",
    parameterType: "PROPORTIONATE",
    relation: { type: "RETAINED_EARNINGS", subType: "asset" },
  },
  純資産合計: {
    sheetType: "集約科目",
    parentAccount: "",
    parameterType: "NONE",
    relation: { type: "NONE", subType: null },
  },
  負債及び純資産合計: {
    sheetType: "集約科目",
    parentAccount: "",
    parameterType: "NONE",
    relation: { type: "NONE", subType: null },
  },
  有形資産投資: {
    sheetType: "CAPEX",
    parentAccount: "設備投資合計",
    parameterType: "PROPORTIONATE",
    relation: { type: "PPE", subType: "investment" },
  },
  無形資産投資: {
    sheetType: "CAPEX",
    parentAccount: "設備投資合計",
    parameterType: "PROPORTIONATE",
    relation: { type: "PPE", subType: "investment" },
  },
  設備投資合計: {
    sheetType: "集約科目",
    parentAccount: "",
    parameterType: "NONE",
    relation: { type: "NONE", subType: null },
  },
  営業利益_CF: {
    sheetType: "集約科目",
    parentAccount: "営業CF合計",
    parameterType: "NONE",
    relation: { type: "NONE", subType: null },
  },
  減価償却費_CF: {
    sheetType: "CF",
    parentAccount: "営業CF合計",
    parameterType: "NONE",
    relation: { type: "NONE", subType: null },
  },
  無形固定資産償却費_CF: {
    sheetType: "CF",
    parentAccount: "営業CF合計",
    parameterType: "NONE",
    relation: { type: "NONE", subType: null },
  },
  運転資本増減: {
    sheetType: "CF",
    parentAccount: "営業CF合計",
    parameterType: "NONE",
    relation: { type: "NONE", subType: null },
  },
  営業CF合計: {
    sheetType: "集約科目",
    parentAccount: "",
    parameterType: "NONE",
    relation: { type: "NONE", subType: null },
  },
  設備投資合計_CF: {
    sheetType: "CF",
    parentAccount: "投資CF合計",
    parameterType: "NONE",
    relation: { type: "NONE", subType: null },
  },
  投資CF合計: {
    sheetType: "集約科目",
    parentAccount: "",
    parameterType: "NONE",
    relation: { type: "NONE", subType: null },
  },

  // MODEL_ACCOUNTSから追加された科目
  売上高1: {
    sheetType: "PL",
    parentAccount: "売上高合計",
    parameterType: "GROWTH_RATE",
    relation: { type: "NONE", subType: null },
  },
  売上高2: {
    sheetType: "PL",
    parentAccount: "売上高合計",
    parameterType: "GROWTH_RATE",
    relation: { type: "NONE", subType: null },
  },
  売上原価1: {
    sheetType: "PL",
    parentAccount: "売上原価合計",
    parameterType: "PERCENTAGE",
    relation: { type: "NONE", subType: null },
  },
  売上原価2: {
    sheetType: "PL",
    parentAccount: "売上原価合計",
    parameterType: "PERCENTAGE",
    relation: { type: "NONE", subType: null },
  },
  広告宣伝費: {
    sheetType: "PL",
    parentAccount: "販管費合計",
    parameterType: "PERCENTAGE",
    relation: { type: "NONE", subType: null },
  },
  物件費: {
    sheetType: "PL",
    parentAccount: "販管費合計",
    parameterType: "PERCENTAGE",
    relation: { type: "NONE", subType: null },
  },
  その他償却費1: {
    sheetType: "PL",
    parentAccount: "販管費合計",
    parameterType: "PERCENTAGE",
    relation: { type: "PPE", subType: "depreciation" },
  },
  その他償却費2: {
    sheetType: "PL",
    parentAccount: "販管費合計",
    parameterType: "PERCENTAGE",
    relation: { type: "PPE", subType: "depreciation" },
  },
  その他流動資産: {
    sheetType: "BS",
    parentAccount: "流動資産合計",
    parameterType: "PROPORTIONATE",
    relation: { type: "NONE", subType: null },
  },
  償却資産1: {
    sheetType: "BS",
    parentAccount: "固定資産合計",
    parameterType: "PROPORTIONATE",
    relation: { type: "PPE", subType: "asset" },
  },
  償却資産2: {
    sheetType: "BS",
    parentAccount: "固定資産合計",
    parameterType: "PROPORTIONATE",
    relation: { type: "PPE", subType: "asset" },
  },
  その他固定資産: {
    sheetType: "BS",
    parentAccount: "固定資産合計",
    parameterType: "PROPORTIONATE",
    relation: { type: "NONE", subType: null },
  },
  その他流動負債: {
    sheetType: "BS",
    parentAccount: "流動負債合計",
    parameterType: "PROPORTIONATE",
    relation: { type: "NONE", subType: null },
  },
  その他固定負債: {
    sheetType: "BS",
    parentAccount: "固定負債合計",
    parameterType: "PROPORTIONATE",
    relation: { type: "NONE", subType: null },
  },
  固定資産投資1: {
    sheetType: "CAPEX",
    parentAccount: "設備投資合計",
    parameterType: "PROPORTIONATE",
    relation: { type: "PPE", subType: "investment" },
  },
  固定資産投資2: {
    sheetType: "CAPEX",
    parentAccount: "設備投資合計",
    parameterType: "PROPORTIONATE",
    relation: { type: "PPE", subType: "investment" },
  },
};

// モデルの勘定科目リスト（元の勘定科目 + 集計科目）
export const MODEL_ACCOUNTS = [
  "売上高1",
  "売上高2",
  "売上原価1",
  "売上原価2",
  "人件費",
  "広告宣伝費",
  "物件費",
  "減価償却費_PL",
  "無形固定資産償却費_PL",
  "その他償却費1",
  "その他償却費2",
  "その他販管費",
  "現預金",
  "売掛金",
  "棚卸資産",
  "その他流動資産",
  "償却資産1",
  "償却資産2",
  "その他固定資産",
  "買掛金",
  "支払手形",
  "その他流動負債",
  "長期借入金",
  "その他固定負債",
  "資本金等",
  "利益剰余金等",
  "固定資産投資1",
  "固定資産投資2",
  "減価償却費_CF",
  "無形固定資産償却費_CF",
];
